server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.108.12.84:3307/liangshan_cloud_dev?useUnicode=true&characterEncoding=utf8
    username: root
    password: Rj2fmOU6QZw6YPRIEslpW6W0807


mybatis:
  mapper-locations: classpath:com/baihao/modules/**/*Mapper.xml
  type-aliases-package: com.baihao.modules.**.entity
  config-location: classpath:config/mybatis-config.xml

#数据库分页插件
pagehelper:
  helper-dialect: mysql  #使用哪种数据库语言
  reasonable: true      #配置分页参数合理化功能，默认是false。 #启用合理化时，如果pageNum<1会查询第一页，如果pageNum>总页数会查询最后一页； #禁用合理化时，如果pageNum<1或pageNum>总页数会返回空数据。
  support-methods-arguments: true  #支持通过Mapper接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
